# Generated by Django 6.0.6 on 2026-06-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('private', 'Личный чат'), ('group', 'Групповой чат')], default='private')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название группы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_key_encrypted', models.TextField(blank=True, null=True, verbose_name='Зашифрованный групповой ключ')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Вложения(массив url)')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('is_encrypted', models.BooleanField(default=True, verbose_name='Зашифровано?')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleated', models.BooleanField(default=False)),
                ('deleated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
