# Generated by Django 6.0.6 on 2026-06-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, help_text="Тип файла: 'image', 'file', 'audio', 'video'", max_length=50, null=True),
        ),
    ]
